# IERG 3320 -- NetworkX Tutorial

### How to create a matrix

* (Simple) Using a list in a list

In [1]:
matrix = list()
for row_index in range(78):
    matrix.append(list())
    for coloum_index in range(78):
        matrix[row_index].append(0)
    

* (Optional) using numpy

In [2]:
import numpy as np
a_matrix = np.matrix([[1,2,3],[11,12,13],[21,22,23]])

print a_matrix 

[[ 1  2  3]
 [11 12 13]
 [21 22 23]]


## How to use NetworkX
### Create a graph

In [3]:
import networkx as nx

# An undirected graph
G = nx.Graph()

# A directed graph
di_G = nx.DiGraph()

## Nodes
Note: We will use di_G since the sociamatrix in our class is a directed graph

In [4]:
# add one node
di_G.add_node(1)

# add multiple nodes
di_G.add_nodes_from([2,3,4,5])

# the node's label can be string
di_G.add_node('Ted')

# check exsiting nodes in the graph
di_G.nodes()

[1, 2, 3, 4, 5, 'Ted']

In [5]:
# remove nodes form the graph
di_G.remove_node('Ted')

# Check the nodes again
di_G.nodes()

[1, 2, 3, 4, 5]

## Edges

Can be directional or undirectional, depending on the graph type

In [6]:
# add one edge (from node 1 to node 2)
di_G.add_edge(1,2)

# add multiple edges
edge_list = [(1, 4), (2, 3), (2, 4), (2, 5)]
di_G.add_edges_from(edge_list)

# remove an edge
di_G.remove_edge(2,5)

# check the edges
di_G.edges()

[(1, 2), (1, 4), (2, 3), (2, 4)]

Edges can have weight (default to be 1)

In [7]:
# Add an edge with weight
di_G.add_edge(3,4,weight=3)

di_G.remove_edge(3,4)

**Important Note**:
* New nodes will be created if the ending node of an edge doesn’t exist.
* When a node is removed, all edges related to it are also removed

In [8]:
# Add an edge with non-exist node
di_G.add_edge(3,6)

di_G.edges()

[(1, 2), (1, 4), (2, 3), (2, 4), (3, 6)]

In [9]:
di_G.nodes()

[1, 2, 3, 4, 5, 6]

In [10]:
# remove node 6
di_G.remove_node(6)

di_G.edges()

[(1, 2), (1, 4), (2, 3), (2, 4)]

## How to analyse the Graph
Properties including:
* Density
* In-degree
* Out-degree
* Betweeness
* Closeness

In [11]:
# Density 
nx.density(di_G)

0.2

In [14]:
# In-degree
members_inDgree = di_G.in_degree()
# Out-degree
members_outDegree = di_G.out_degree()

print 'The in-degrees for all nodes are:', members_inDgree
print 'The out-degree for all nodes are:', members_outDegree

# Betweeness
# Closeness

The in-degrees for all nodes are: {1: 0, 2: 1, 3: 1, 4: 2, 5: 0}
The out-degree for all nodes are: {1: 2, 2: 2, 3: 0, 4: 0, 5: 0}


In [ ]:
# (Optional) Draw the graph using matplotlib
import matplotlib.pyplot as plt
nx.draw(di_G)
plt.show()